#!/bin/bash

echo "creating makefile"
qmake dsipcom.pro
if [ $? = 0 ]; then
	echo "done"
fi

#make clean
make all 2> compile.log
if [ $? = 0 ]; then
	 echo "done. dSipCom ready"
fi
less compile.log


