#!/bin/bash

if [ -e "Makefile" ]; then
	echo "removing Makefile"
	rm Makefile
fi

echo "creating Makefile"
qmake-qt4 dsipcom.pro
if [ $? = 0 ]; then
	echo "done"
fi

make all 2> compile.log
if [ $? = 0 ]; then
	 echo "done. dSipCom ready"
fi

if [ -s "compile.log" ]; then
	less compile.log
	else
	rm compile.log
fi
